// Generated by CoffeeScript 1.7.1
'use strict';

/* App module */
var app;

app = angular.module('betaseries-chrome', ['ngRoute']);

app.service('db', db);

app.factory('Auth', function(db) {
  return new Auth(db);
});

app.factory('Ajax', function(Auth, $http) {
  return new Ajax(Auth, $http);
});

app.factory('Betaseries', function(Ajax, db) {
  return new Betaseries(Ajax, db);
});

app.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/connection', {
      templateUrl: 'partials/connection.html',
      controller: ConnectionCtrl,
      token: false
    }).when('/my-episodes', {
      templateUrl: 'partials/my-episodes.html',
      controller: MyEpisodesCtrl,
      token: true
    }).when('/episodes/:episode/comments', {
      templateUrl: 'partials/episode-comments.html',
      controller: EpisodeCommentsCtrl,
      token: false
    }).otherwise({
      redirectTo: '/error'
    });
  }
]);

app.run(function($rootScope, $location, Auth) {
  var defaultPath;
  defaultPath = Auth.isLogged() ? '/my-episodes' : '/connection';
  $location.path(defaultPath);
  return $rootScope.$on('$routeChangeStart', function(event, currRoute, prevRoute) {
    if (currRoute.token && !Auth.isLogged()) {
      return $location.path('/connection');
    }
  });
});
