// Generated by CoffeeScript 1.3.3
var App;

App = (function() {

  function App() {}

  App.prototype.historic = null;

  App.prototype.view = null;

  App.prototype.init = function() {
    var homepage;
    DB.init();
    Fx.checkVersion();
    homepage = Fx.logged() ? 'MyEpisodes' : 'Connection';
    this.historic = new Historic(this);
    this.view = new View(this);
    return this.view.load(homepage);
  };

  App.prototype.listen = function() {
    $('#logoLink').click(function() {
      return Fx.openTab(ajax.site_url, true);
    }).attr('title', __("logo"));
    $('#versionLink').click(function() {
      return Fx.openTab('https://chrome.google.com/webstore/detail/dadaekemlgdonlfgmfmjnpbgdplffpda', true);
    }).attr('title', __("version"));
    $('.Menu a').live('click', function() {
      var id;
      event.preventDefault();
      id = $(this).attr('id').substring(5);
      if (id === 'Options') {
        return Fx.openTab(chrome.extension.getURL('../html/options.html'), true);
      } else if (id === 'Logout') {
        return Fx.logout();
      } else {
        return BS.load(id);
      }
    });
    $('#back').click(function() {
      Historic.back();
      return false;
    }).attr('title', __("back"));
    $('#sync').click(function() {
      return BS.refresh();
    }).attr('title', __('sync'));
    $('#notifications').click(function() {
      BS.load('MemberNotifications');
      return false;
    }).attr('title', __('notifs'));
    $('#menu').click(function() {
      if (BS.currentView.id === 'Menu') {
        return this.historic.refresh();
      } else {
        return this.view.load('Menu');
      }
    }).attr('title', __('menu'));
    return $('#message').on('click', '.close', function() {
      event.preventDefault();
      return $('#message').fadeOut();
    });
  };

  return App;

})();
