// Generated by CoffeeScript 1.7.1

/**
 * Auth class
 * @param {object} Database
 */
var Auth;

Auth = (function() {
  function Auth(db) {
    this.db = db;
  }


  /**
  * Returns true if the user is logged
  * @return {boolean}
   */

  Auth.prototype.isLogged = function() {
    return this.db.get('session') != null;
  };


  /**
  * Get token of current session
  * @return {string|undefined}
   */

  Auth.prototype.getToken = function() {
    var session;
    session = this.db.get('session');
    if (session) {
      return session.token;
    } else {
      return void 0;
    }
  };

  return Auth;

})();
