// Generated by CoffeeScript 1.3.3

chrome.runtime.onInstalled.addListener(function(details) {
  DB.init();
  return Badge.init();
});

chrome.alarms.create('badge_update', {
  delayInMinutes: 0,
  periodInMinutes: 30
});

chrome.alarms.onAlarm.addListener(function(alarm) {
  if (alarm.name === 'badge_update' && Fx.logged()) {
    return Badge.update();
  }
});
