// Generated by CoffeeScript 1.3.3
var Cache,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Cache = {
  force: function(view) {
    var views;
    views = DB.get('views', {});
    if (views[view] != null) {
      views[view].force = true;
      return DB.set('views', views);
    }
  },
  getSize: function() {
    var count, i, j, list;
    count = 0;
    list = ['options', 'version', 'session', 'badge', 'historic'];
    for (i in localStorage) {
      j = localStorage[i];
      if (__indexOf.call(list, i) < 0) {
        count += Fx.getCacheSize(i);
      }
    }
    return count;
  },
  remove: function() {
    var i, j, list, _results;
    list = ['options', 'version', 'session', 'badge', 'historic'];
    _results = [];
    for (i in localStorage) {
      j = localStorage[i];
      if (__indexOf.call(list, i) < 0) {
        _results.push(DB.remove(i));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  }
};
