// Generated by CoffeeScript 1.3.3
var Cache,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Cache = {
  force: function(view) {
    var views;
    views = DB.get('views', {});
    if (views[view] != null) {
      views[view].force = true;
      return DB.set('views', views);
    }
  },
  getSize: function() {
    var count, i, j, list;
    count = 0;
    list = ['options', 'version', 'session', 'badge', 'historic'];
    for (i in localStorage) {
      j = localStorage[i];
      if (__indexOf.call(list, i) < 0) {
        count += Fx.getCacheSize(i);
      }
    }
    return count;
  },
  remove: function() {
    var i, j, todelete, _i, _len;
    todelete = [];
    for (i in localStorage) {
      j = localStorage[i];
      if (i.indexOf('badge') !== 0 && i.indexOf('historic') !== 0 && i.indexOf('member' + DB.get('session').login + '.notifs') !== 0 && i.indexOf('options') !== 0 && i.indexOf('session') !== 0 && i.indexOf('version') !== 0) {
        todelete.push(i);
      }
    }
    for (_i = 0, _len = todelete.length; _i < _len; _i++) {
      i = todelete[_i];
      DB.remove(i);
    }
    return true;
  }
};
