// Generated by CoffeeScript 1.7.1

/**
 * Popup controller
 * @param {[type]} $scope     [description]
 * @param {[type]} Betaseries [description]
 */
var ConnectionCtrl, EpisodeCommentsCtrl, HeaderCtrl, MyEpisodesCtrl;

HeaderCtrl = function($scope, Betaseries) {
  return $scope.sync = function() {
    return Betaseries.refresh();
  };
};


/**
 * Connection - view
 * @param {object} $scope    
 * @param {object} $location 
 * @param {Ajax} Ajax      
 * @param {db} db
 */

ConnectionCtrl = function($scope, $location, Ajax, db) {
  $scope.lbl_login = 'Pseudo';
  $scope.lbl_password = 'Mot de passe';
  $scope.lbl_sign_in = 'Se connecter';
  $scope.lbl_sign_up = "S'inscrire";
  $('#about').height(200);
  $('.nano').nanoScroller({});
  return $scope.sign_in = function() {
    var params;
    params = {
      "login": $scope.login,
      "password": $.md5($scope.password)
    };
    return Ajax.post('/members/auth', params, function(data) {
      db.set('session', {
        "login": data.user.login,
        "token": data.token
      });
      return $location.path('/my-episodes');
    });
  };
};


/**
 * My episodes - view
 * @param {object} $scope
 */

MyEpisodesCtrl = function($scope, $location, Betaseries) {
  Betaseries.load('myEpisodes', {
    "subtitles": "all"
  }, function(shows) {
    $scope.shows = shows;
    $('#about').height(200);
    return $('.nano').nanoScroller({});
  });
  $scope.watched = function(show, episode) {
    var found, i, length, shows;
    shows = $scope.shows;
    found = false;
    i = 0;
    while (!found) {
      if (show.unseen[i].title === episode.title) {
        found = true;
      } else {
        i++;
      }
    }
    length = show.unseen.length;
    show.remaining = length - 1;
    show.unseen = show.unseen.slice(i + 1, length);
    found = false;
    i = 0;
    while (!found) {
      if (shows[i].title === show.title) {
        found = true;
      } else {
        i++;
      }
    }
    if (show.unseen.length > 0) {
      shows[i] = show;
      return Betaseries.save(shows);
    } else {
      return delete show[i];
    }
  };
  return $scope.go_comments = function(episode) {
    return $location.path('/episodes/' + episode + '/comments');
  };
};


/**
 * Episode comments - view
 * /episode/:id/comments
 */

EpisodeCommentsCtrl = function($scope, $routeParams, Betaseries) {
  return Betaseries.load('episodeComments', {
    "type": "episode",
    "id": $routeParams.episode,
    "nbpp": 500,
    "since_id": null,
    "order": "asc"
  }, function(comments) {
    $scope.comments = comments;
    return console.log(comments);
  });
};
