// Generated by CoffeeScript 1.3.1
var Fx, __;

__ = function(msgname, placeholders) {
  if (msgname) {
    return chrome.i18n.getMessage(msgname, placeholders);
  }
};

Fx = {
  openTab: function(url, active) {
    if (active == null) {
      active = false;
    }
    chrome.tabs.create({
      "url": url,
      "active": active
    });
    return false;
  },
  concat: function() {
    var i, j, k, l, n, ret;
    ret = {};
    n = 0;
    for (i in arguments) {
      j = arguments[i];
      for (k in j) {
        l = j[k];
        if (n < 20) {
          ret[n] = l;
          n++;
        }
      }
    }
    return ret;
  },
  subFirst: function(str, nbr) {
    var strLength, strSub;
    strLength = str.length;
    strSub = str.substring(0, nbr);
    if (strSub.length < strLength) {
      strSub += '..';
    }
    return strSub;
  },
  subLast: function(str, nbr) {
    var strLength, strSub;
    strLength = str.length;
    strSub = str.substring(strLength, Math.max(0, strLength - nbr));
    if (strSub.length < strLength) {
      strSub = '..' + strSub;
    }
    return strSub;
  },
  updateHeight: function(top) {
    if (top == null) {
      top = false;
    }
    return setTimeout((function() {
      var maxHeight, params;
      maxHeight = DB.get('options').max_height;
      $('#about').height(maxHeight);
      params = top ? {
        scroll: 'top'
      } : {};
      return $('.nano').nanoScroller(params);
    }), 500);
  },
  toUpdate: function(view) {
    var views;
    views = DB.get('views');
    if (views[view] != null) {
      views[view].force = true;
      return DB.set('views', views);
    }
  },
  getVersion: function() {
    return chrome.app.getDetails().version;
  },
  getNumber: function(season, episode) {
    var number;
    number = 'S';
    if (season <= 9) {
      number += '0';
    }
    number += season;
    number += 'E';
    if (episode <= 9) {
      number += '0';
    }
    number += episode;
    return number;
  },
  displayNumber: function(number) {
    var res;
    res = '#';
    if (number[1] !== '0') {
      res += number[1];
    }
    res += number[2];
    res += number[4];
    res += number[5];
    return res;
  },
  splitNumber: function(number) {
    var episode, season;
    season = '';
    if (number[1] !== '0') {
      season += number[1];
    }
    season += number[2];
    episode = '';
    if (number[4] !== '0') {
      episode += number[4];
    }
    episode += number[5];
    return {
      season: season,
      episode: episode
    };
  },
  getCacheSize: function(key) {
    var size;
    if (key != null) {
      size = Math.floor(JSON.stringify(localStorage[key]).length);
    } else {
      size = Math.floor(JSON.stringify(localStorage).length);
    }
    return size;
  },
  getCacheFormat: function(size) {
    if (size < 1000) {
      return size + ' o';
    } else if (size < 1000 * 1000) {
      return (Math.floor(size / 100) / 10) + ' Ko';
    } else {
      return (Math.floor(size / 1000) / 1000) + ' Mo';
    }
  },
  needUpdate: function() {
    return __('no_data_found');
  },
  checkVersion: function() {
    var currVersion, newVersion, version;
    version = DB.get('version', 0);
    currVersion = Fx.getVersion();
    newVersion = version !== currVersion;
    $('#versionLink').text(Fx.getVersion());
    if (newVersion) {
      BS.load('logout');
      return $('#message').html(__('new_version')).show();
    }
  }
};
