// Generated by CoffeeScript 1.3.3
var Historic,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Historic = (function() {

  function Historic(app) {
    this.app = app;
  }

  Historic.prototype.refresh = function() {
    var args, historic, length;
    historic = DB.get('historic');
    length = historic.length;
    args = historic[length - 1].split('.');
    this.app.view.load.apply(this.app.view, args);
    return this.display(length);
  };

  Historic.prototype.save = function() {
    var blackpages, historic, length, view;
    historic = DB.get('historic');
    length = historic.length;
    blackpages = ['Connection', 'Registration', 'Menu'];
    view = this.app.view.infos.id;
    if (historic[length - 1] !== view && !(__indexOf.call(blackpages, view) >= 0)) {
      historic.push(view);
      DB.set('historic', historic);
      length++;
    }
    return this.display(length);
  };

  Historic.prototype.back = function() {
    var args, historic, length;
    historic = DB.get('historic');
    if ((length = historic.length) >= 2) {
      historic.pop();
      args = historic[length - 2].split('.');
      this.app.view.load.apply(this.app.view, args);
      DB.set('historic', historic);
      length--;
    }
    this.display(length);
    return false;
  };

  Historic.prototype.display = function(n) {
    var blackpages, view;
    view = this.app.view.infos.id;
    blackpages = ['Connection', 'Registration', 'Menu'];
    if (n >= 2 && !(__indexOf.call(blackpages, view) >= 0)) {
      return $('#back').show();
    } else {
      return $('#back').hide();
    }
  };

  return Historic;

})();
