// Generated by CoffeeScript 1.3.1
var Historic,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Historic = {
  refresh: function() {
    var args, historic, length;
    historic = DB.get('historic');
    length = historic.length;
    args = historic[length - 1].split('.');
    return BS.load.apply(BS, args);
  },
  save: function() {
    var blackpages, historic, length, view;
    historic = DB.get('historic');
    length = historic.length;
    blackpages = ['connection', 'registration', 'menu'];
    view = BS.currentView.id;
    if (historic[length - 1] !== view && !(__indexOf.call(blackpages, view) >= 0)) {
      historic.push(view);
      DB.set('historic', historic);
      if (length === 1) {
        return $('#back').show();
      }
    }
  },
  back: function() {
    var args, historic, length;
    historic = DB.get('historic');
    if ((length = historic.length) >= 2) {
      historic.pop();
      args = historic[length - 2].split('.');
      console.log(args);
      BS.load.apply(BS, args);
      DB.set('historic', historic);
      if (length === 2) {
        $('#back').hide();
      }
    }
    return false;
  }
};
