// Generated by CoffeeScript 1.7.1

/**
 * View class
 */
var View;

View = (function() {
  function View(db, params, callback) {
    this.db = db;
    this.params = params;
    this.callback = callback;
    this.type = 'get';
    this.path = '';
    this.store = '';
    this.node = '';
  }

  return View;

})();
