// Generated by CoffeeScript 1.3.3
var View_Blog;

View_Blog = (function() {

  function View_Blog() {}

  View_Blog.prototype.init = function() {
    this.id = 'Blog';
    return this.name = 'Blog';
  };

  View_Blog.prototype.update = function() {
    return $.ajax({
      type: 'GET',
      url: 'https://www.betaseries.com/blog/feed/',
      dataType: 'xml',
      async: false,
      success: function(data) {
        var article, blog, i, item, items, _i, _ref;
        items = $(data).find('item');
        blog = [];
        for (i = _i = 0, _ref = Math.min(10, items.length); 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          item = $(items[i]);
          article = {};
          article.title = item.find('title').text();
          article.description = item.find('description').text();
          article.link = item.find('link').text();
          blog.push(article);
        }
        DB.set('blog', blog);
        return BS.display();
      }
    });
  };

  View_Blog.prototype.content = function() {
    var article, data, i, link, output, title, _i, _len;
    output = '';
    data = DB.get('blog', null);
    if (!data) {
      return Fx.needUpdate();
    }
    for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
      article = data[i];
      title = article.title.substring(0, 40);
      if (article.title.length > 40) {
        title += '..';
      }
      output += '<div class="showtitle">' + title;
      output += '</div>';
      link = '<a href="#" link="' + article.link + '" class="display_postblog">(' + __('read_article') + ')</a>';
      output += '<div>' + article.description.replace(/<a(.*)a>/, link) + '</div>';
      output += '<div style="height:11px;"></div>';
    }
    return output;
  };

  View_Blog.prototype.listen = function() {
    return $('.display_postblog').on('click', function() {
      var link;
      event.preventDefault();
      link = $(this).attr('link');
      return Fx.openTab(link, true);
    });
  };

  return View_Blog;

})();
