// Generated by CoffeeScript 1.3.3
var View_MemberShows,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

View_MemberShows = (function() {

  function View_MemberShows() {
    this.init = __bind(this.init, this);

  }

  View_MemberShows.prototype.init = function(login) {
    var _ref;
    if (login == null) {
      login = (_ref = DB.get('session')) != null ? _ref.login : void 0;
    }
    this.id = 'MemberShows.' + login;
    this.url = '/members/infos/' + login;
    this.login = login;
    this.name = 'MemberShows';
    return this.root = 'member';
  };

  View_MemberShows.prototype.update = function(data) {
    var i, s, shows, _ref;
    shows = DB.get('member.' + this.login + '.shows', {});
    _ref = data.shows;
    for (i in _ref) {
      s = _ref[i];
      if (s.url in shows) {
        shows[s.url].archive = s.archive;
      } else {
        shows[s.url] = {
          url: s.url,
          title: s.title,
          archive: s.archive,
          hidden: false
        };
      }
    }
    return DB.set('member.' + this.login + '.shows', shows);
  };

  View_MemberShows.prototype.content = function() {
    var data, i, output, show;
    data = DB.get('member.' + this.login + '.shows', null);
    if (!data) {
      return Fx.needUpdate();
    }
    output = '';
    for (i in data) {
      show = data[i];
      output += '<div class="episode" id="' + show.url + '">';
      if (show.archive === '1') {
        output += '<img src="../img/folder_off.png" class="icon-3" /> ';
      } else {
        output += '<img src="../img/folder.png" class="icon-3" /> ';
      }
      output += '<a href="" url="' + show.url + '" class="epLink display_show">' + show.title + '</a>';
      output += '</div>';
    }
    return output;
  };

  View_MemberShows.prototype.listen = function() {
    $('#showsArchive').on('click', function() {
      var show,
        _this = this;
      show = $(this).attr('href').substring(1);
      $(this).find('span').toggleClass('imgSyncOff imgSyncOn');
      ajax.post("/shows/archive/" + show, "", function() {
        Cache.force('MyEpisodes.all');
        Cache.force('Member.' + DB.get('session').login);
        Badge.search_episodes();
        $(_this).html('<span class="imgSyncOff"></span>' + __('show_unarchive'));
        return $(_this).attr('id', 'showsUnarchive');
      }, function() {
        return registerAction("/shows/archive/" + show, "");
      });
      return false;
    });
    return $('#showsUnarchive').on('click', function() {
      var show,
        _this = this;
      show = $(this).attr('href').substring(1);
      $(this).find('span').toggleClass('imgSyncOff imgSyncOn');
      ajax.post("/shows/unarchive/" + show, "", function() {
        Cache.force('MyEpisodes.all');
        Cache.force('Member.' + DB.get('session').login);
        Badge.search_episodes();
        $(_this).html('<span class="imgSyncOff"></span>' + __('show_archive'));
        return $(_this).attr('id', 'showsArchive');
      }, function() {
        return registerAction("/shows/unarchive/" + show, "");
      });
      return false;
    });
  };

  return View_MemberShows;

})();
