// Generated by CoffeeScript 1.3.3
var View_MemberTimeline,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

View_MemberTimeline = (function() {

  function View_MemberTimeline() {
    this.init = __bind(this.init, this);

  }

  View_MemberTimeline.prototype.init = function() {
    var _ref;
    this.id = 'MemberTimeline';
    this.name = 'MemberTimeline';
    this.url = '/timeline/friends';
    this.params = '&number=10';
    this.root = 'timeline';
    return this.login = (_ref = DB.get('session')) != null ? _ref.login : void 0;
  };

  View_MemberTimeline.prototype.update = function(data) {
    return DB.set('member.' + this.login + '.timeline', data);
  };

  View_MemberTimeline.prototype.content = function() {
    var data, n, new_date, output, time;
    output = '';
    time = '';
    data = DB.get('member.' + this.login + '.timeline', null);
    if (!data) {
      return Fx.needUpdate();
    }
    for (n in data) {
      new_date = date('D d F', data[n].date);
      if (new_date !== time) {
        time = new_date;
        output += '<div class="title">' + time + '</div>';
      }
      output += '<div class="event ' + date('D', data[n].date).toLowerCase() + '">';
      output += '<b>' + date('H:i', data[n].date) + '</b> ';
      output += '<span class="login">' + data[n].login + '</span> ' + data[n].html;
      output += '</div>';
    }
    return output;
  };

  return View_MemberTimeline;

})();
