// Generated by CoffeeScript 1.6.2
var View_Menu,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

View_Menu = (function() {
  function View_Menu() {
    this.init = __bind(this.init, this);
  }

  View_Menu.prototype.init = function() {
    this.id = 'Menu';
    return this.name = 'Menu';
  };

  View_Menu.prototype.content = function() {
    var m, menu_order, output, style, _i, _len;

    output = '';
    menu_order = DB.get('options').menu_order;
    for (_i = 0, _len = menu_order.length; _i < _len; _i++) {
      m = menu_order[_i];
      if (!m.visible) {
        continue;
      }
      style = '';
      if (m.img_style != null) {
        style = 'style="' + m.img_style + '" ';
      }
      output += '<a href="" id="menu-' + m.name + '" class="menulink">';
      output += '<img src="' + m.img_path + '" ' + style + '/>';
      output += __('menu_' + m.name) + '</a>';
    }
    return output;
  };

  View_Menu.prototype.listen = function() {
    return $('.Menu').on('click', '.menulink', function() {
      var id;

      event.preventDefault();
      id = $(this).attr('id').substring(5);
      if (id === 'Options') {
        return Fx.openTab(chrome.extension.getURL('../html/options.html'), true);
      } else if (id === 'Logout') {
        return Fx.logout();
      } else {
        return app.view.load(id);
      }
    });
  };

  return View_Menu;

})();
