// Generated by CoffeeScript 1.3.3
var View_Show,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

View_Show = (function() {

  function View_Show() {
    this.init = __bind(this.init, this);

  }

  View_Show.prototype.init = function(url) {
    var _ref;
    this.id = 'Show.' + url;
    this.url = '/shows/display/' + url;
    this.show = url;
    this.name = 'Show';
    this.root = 'show';
    return this.login = (_ref = DB.get('session')) != null ? _ref.login : void 0;
  };

  View_Show.prototype.update = function(data) {
    data.is_in_account = data.is_in_account === "1";
    data.archive = data.archive === "1";
    return DB.set('show.' + this.show, data);
  };

  View_Show.prototype.content = function() {
    var data, genres, i, k, note, output, v, _i, _ref, _ref1;
    data = DB.get('show.' + this.show, null);
    if (!data) {
      return Fx.needUpdate();
    }
    output = '<div class="title">';
    output += '<div class="fleft200">' + data.title + '</div>';
    output += '<div class="fright200 aright">';
    if (data.note != null) {
      note = Math.floor(data.note.mean);
      for (i = _i = 1; 1 <= note ? _i <= note : _i >= note; i = 1 <= note ? ++_i : --_i) {
        output += '<img src="../img/star.gif" /> ';
      }
    }
    output += '</div>';
    output += '<div class="clear"></div>';
    output += '</div>';
    output += '<div>';
    output += '<div class="fleft200">';
    genres = [];
    _ref = data.genres;
    for (k in _ref) {
      v = _ref[k];
      genres.push(v);
    }
    output += genres.join(', ') + ' | ';
    if (data.status != null) {
      output += __(data.status.toLowerCase());
    }
    output += '</div>';
    output += '<div class="fright200 aright">';
    if (((_ref1 = data.note) != null ? _ref1.mean : void 0) != null) {
      output += data.note.mean + '/5 (' + data.note.members + ')';
    }
    output += '</div>';
    output += '</div>';
    if (data.banner != null) {
      output += '<img src="' + data.banner + '" width="290" height="70" alt="banner" style="margin-top: 10px;" />';
    }
    if (data.description != null) {
      output += '<div class="title2">' + __('synopsis') + '</div>';
      output += '<div style="margin-right:5px; text-align:justify;">' + data.description + '</div>';
    }
    output += '<div class="title2">' + __('actions') + '</div>';
    output += '<a href="" class="link display_episodes" url="' + data.url + '"><span class="imgSyncNo"></span>Voir les épisodes</a>';
    if (data.is_in_account && data.archive) {
      output += '<a href="#' + data.url + '" id="showsUnarchive" class="link">' + '<span class="imgSyncOff"></span>' + __('show_unarchive') + '</a>';
    } else if (data.is_in_account && !data.archive) {
      output += '<a href="#' + data.url + '" id="showsArchive" class="link">' + '<span class="imgSyncOff"></span>' + __('show_archive') + '</a>';
    }
    if (data.is_in_account) {
      output += '<a href="#' + data.url + '" id="showsRemove" class="link">' + '<span class="imgSyncOff"></span>' + __('show_remove') + '</a>';
    } else {
      output += '<a href="#' + data.url + '" id="showsAdd" class="link">' + '<span class="imgSyncOff"></span>' + __('show_add') + '</a>';
    }
    return output;
  };

  return View_Show;

})();
